### ISSUE TITLE
Issue with $http as a dependency inside of a service

### ISSUE THREAD

**Issue by mitchogaard** [tennisgent/quickmock#12]
I've got a Plunkr here that shows an issue with trying to use $httpBackend inside of a test and a service   (named _Service_)that uses $http that I'm trying to quickmock. QuickMock doesn't seem to handle the mocking/providing of $http properly. That is, assuming I'm doing everything properly here: https://plnkr.co/edit/1ZxwT8KoZAVcqOiuJDDB?p=preview

Note that the only test where QuickMock does not provide _Service_ passes.

**Comment by tennisgent** [comment]
It looks like you weren't injecting `$httpBackend` properly. Because of the way quickmock works, you can't use the typical global `inject()` function. You have to use quickmock's inject method, as shown in an updated version of [your plunker here](https://plnkr.co/edit/IU75mebN0YA14RvtwpkS?p=preview) and in this snippet below:  

``` javascript
service = quickmock({
    providerName: 'Service',
    moduleName: 'services',
    mockModules: ['mocks'],
    inject: function(_$httpBackend_){
         $httpBackend = _$httpBackend_;
    }
});
```

Hope that helps. If it does, feel free to close out this issue. If not, let me know and I'll revisit the issue.

**Comment by mitchogaard** [comment]
Holy crap that's __very__ useful information. I don't recall seeing that in the docs anywhere. Can we get an update somewhere that includes why this is or at least an example such as the one you provided? Thank you very much.

**Comment by tennisgent** [comment]
@mitchogaard 
Just FYI, I added this info to the [README](https://github.com/tennisgent/quickmock/blob/master/README.md#the-config-object). Sorry that there previously wasn't any documentation for this feature.
